config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin, path: Spree.admin_path do
    resources :content_fragments
    resources :products do
      resources :content_fragments do
        collection do
          post :update_positions
        end
      end
    end
  end
end

app/models/spree/content_fragment.rb
module Spree
  # Represents a fragment of content. It can belong to any kind of object
  # although at the time of writing, only products are supported (see the controller)
  class ContentFragment < Spree::Base
    acts_as_list scope: %i(parent_id parent_type)
    belongs_to :parent, polymorphic: true

    validates :title, presence: true
    validates :position, presence: true, numericality: true

    default_scope -> { order(:position) }

    ## Spree preferences


    enum content_position_h: { left: 0, center: 1, right: 2 }
    enum content_position_v: { top: 0, middle: 1, bottom: 2 }

    # Apply styling appropriate for this file
    has_attached_file :background_media,
                        styles: lambda { |a| a.instance.check_file_type}, :default_url => "missing.png",
                        default_style: :medium,
                        processors: lambda { |a| a.is_video_type? ? [ :transcoder ] : [ :thumbnail ] }

    #
    validates_attachment_content_type :background_media, :content_type => /.*/

    # Process media in background with delayed_paperclip
    process_in_background :background_media, processing_image_url: lambda { |a| a.instance.processing_image_path("missing.jpg")}

    # The path of the image that will be shown while the file is loading
    def processing_image_path(image_name)
      "/assets/" + Rails.application.assets.find_asset(image_name).digest_path
    end

    # IMPORTANT! The ffmpeg library has to added to the server machine.
    # It can be uploaded from the official website https://www.ffmpeg.org/
    def check_file_type
      if is_image_type?
        {
          thumb: '100x100>',
          medium: '640x360>',
          large: '1920x1080>'
        }
      elsif is_video_type?
        {
          thumb:          { :geometry => "100x100#", format: 'jpg', :time => 5 },
          mp4_sd:         { :geometry => "640x360#", format: 'mp4', :processors => [:transcoder] },
          mp4_hd:         { :geometry => "1920x1080#", format: 'mp4', :processors => [:transcoder] },
          #webm_sd:        { :geometry => "640x360#", format: 'webm', :processors => [:transcoder] },
          webm_hd:        { :geometry => "1920x1080#", format: 'webm', :processors => [:transcoder] }
        }
      else
        {}
      end
    end

    def view_model
      ContentFragmentViewModel.new(self)
    end

    # Method returns true if file's content type contains word 'image', overwise false
    def is_image_type?
      background_media.content_type =~ %r(image)
    end

    # Method returns true if file's content type contains word 'video', overwise false
    def is_video_type?
      background_media.content_type =~ %r(video)
    end

  end
end

app/models/spree/content_fragment_view_model.rb
module Spree
  class ContentFragmentViewModel
    attr_reader :fragment

    def initialize(fragment)
      @fragment = fragment
    end

    delegate :title, to: :fragment
    delegate :body, to: :fragment

    def tag_id
      "content_fragment_#{@fragment.id}"
    end

    def tag_classes
      "#{'fullscreen' if @fragment.fullpage} content-position-ver-#{@fragment.content_position_v} content-position-hor-#{@fragment.content_position_h}"
    end

    def style_tag_content
      scss <<-SCSS
        ##{tag_id} {
          #{background_style}
          #{@fragment.style}
        }
      SCSS
    end

    protected

    def background_style
      return nil unless @fragment.is_image_type?
      "background-image: url(#{@fragment.background_media.url(:original)});"
    end

    def scss(string)
      return '' if string.blank?
      Sass::Engine.new(string, syntax: :scss).render
    end
  end
end

app/models/spree/product_decorator.rb
module Spree
  # Add an association to Products so its content fragments can be easily loaded
  Product.class_eval do
    has_many :content_fragments, as: :parent
  end


end

app/controllers/spree/admin/content_fragments_controller.rb
module Spree
  module Admin
    class ContentFragmentsController < ResourceController
      belongs_to 'spree/product', find_by: :slug

      def index
        @content_fragments = @product.content_fragments
      end
    end
  end
end

app/views/spree/admin/content_fragments/_form.html.erb
<%= f.hidden_field :position %>
<div class="row" data-hook="admin_content_fragment_form_fields">
  <div class="col-md-8" data-hook="admin_content_fragment_form_left">
    <div class="form-group">
      <%= f.label :title %> <span class="required">*</span>
      <%= f.text_field :title, class: 'form-control' %>
      <%= f.error_message_on :title %>
    </div>

    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, rows: 12, class: 'form-control' %>
      <%= f.error_message_on :body %>
    </div>

    <div class="form-group">
      <%= f.label :style %>
      <%= f.text_area :style, rows: 12, class: 'form-control' %>
    </div>
  </div>

  <div class="col-md-4" data-hook="admin_content_fragment_form_right">

    <div class="form-group">
      <%= f.label 'Background image or video' %>
      <% if f.object.background_media.present? %>
        <p>
          <%= image_tag f.object.background_media.url(:thumb) %>
        </p>
      <% end %>
      <%= f.file_field :background_media, class: 'form-control' %>
    </div>

    <hr>

    <div class="form-group">
      <%= f.label 'Youtube Video ID' %>
      <%= f.text_field :youtube_video_id, class: 'form-control' %>
    </div>

    <hr>

    <h4>Size</h4>
    <div class="form-group">
      <%= f.label :fullpage do %>
        <%= f.check_box :fullpage, wrapper_html: { tag_name: 'span'} %>
        Fullscreen <br>
        <span class="text-muted">Fit content fragment to viewport height and width.</span>
      <% end %>
    </div>

    <hr>

    <h4>Content</h4>
    <div class="form-group">
      <%= f.label :box_around_content do %>
        <%= f.check_box :box_around_content %>
        Box around content
        <p class="text-muted"></p>
      <% end %>
    </div>


    <h4>Content Position</h4>
    <div class="well" id="position-select-wrapper">
      <div class="row">
        <div class="col-sm-4">
          <%= f.radio_button :content_position, 1 %>
          <%= f.radio_button :content_position, 4 %>
          <%= f.radio_button :content_position, 7 %>
        </div>
        <div class="col-sm-4">
          <%= f.radio_button :content_position, 2 %>
          <%= f.radio_button :content_position, 5 %>
          <%= f.radio_button :content_position, 8 %>
        </div>
        <div class="col-sm-4">
          <%= f.radio_button :content_position, 3 %>
          <%= f.radio_button :content_position, 6 %>
          <%= f.radio_button :content_position, 9 %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/spree/admin/content_fragments/edit.html.erb
<%= render partial: 'spree/admin/shared/product_tabs', locals: { current: :content_fragments } %>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @product } %>

<%= form_for [:admin, @product, @content_fragment], html: { multipart: true } do |f| %>
  <fieldset data-hook="edit_content_fragment">
    <%= render partial: 'form', locals: { f: f } %>

    <div class="form-actions" data-hook="buttons">
      <%= button Spree.t('actions.update'), 'save' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), spree.admin_product_content_fragments_url(@product), icon: 'delete', id: 'cancel_link' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/content_fragments/index.html.erb
<%= render partial: 'spree/admin/shared/product_tabs', locals: { current: :content_fragments } %>

<% content_for :page_actions do %>
  <%= button_link_to(Spree.t(:new_content_fragment), spree.new_admin_product_content_fragment_url(@product), { class: "btn-success", icon: 'add', id: 'new_content_fragment_link' }) if can? :create, Spree::ContentFragment %>
<% end %>

<% unless @content_fragments.any? %>
  <div class="alert alert-warning">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::ContentFragment)) %>.
  </div>
<% else %>
  <table class="table sortable" id='listing_content_fragments' data-hook data-sortable-link="<%= update_positions_admin_product_content_fragments_url(@product) %>">
    <thead>
      <tr data-hook="content_fragments_header">
        <th></th>
        <th><%= Spree.t(:position) %></th>
        <th><%= Spree.t(:html_tag_id) %></th>
        <th></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @content_fragments.each do |content_fragment|
           @edit_url = edit_admin_content_fragment_path(content_fragment)
           @delete_url = admin_content_fragment_path(content_fragment)
      %>
        <tr id="<%= spree_dom_id content_fragment %>" data-hook="content_fragment_row">
          <td class="move-handle text-center">
            <% if can? :edit, content_fragment %>
              <span class="icon icon-move handle"></span>
            <% end %>
          </td>
          <td><%= content_fragment.title %></td>
          <td>#<%= content_fragment.view_model.tag_id %></td>
          <td><%= image_tag content_fragment.background_media.url(:thumb) %></td>
          <td class="actions actions-2 text-center">
            <%= link_to_edit(content_fragment, no_text: true) if can? :create, content_fragment %>
            <%= link_to_delete(content_fragment, no_text: true) if can? :create, content_fragment %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/admin/content_fragments/new.html.erb
<%= render partial: 'spree/admin/shared/product_tabs', locals: { current: :content_fragments } %>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @product } %>

<% content_for :page_title do %>
  <%= Spree.t(:new_content_fragment) %>
<% end %>

<%= form_for [:admin, @product, @content_fragment], html: { multipart: true } do |f| %>
  <fieldset data-hook="new_content_fragment">
    <%= render partial: 'form', locals: { f: f } %>

    <div class="form-actions" data-hook="buttons">
      <%= button Spree.t('actions.create'), 'save' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), spree.admin_product_content_fragments_url(@product), icon: 'delete', id: 'cancel_link' %>
    </div>
  </fieldset>
<% end %>